# Курс "R, визуализация и статистика"

### Установка R и RStudio.
[R](https://www.r-project.org/), [RStudio](https://www.rstudio.com/products/rstudio/download/#download), [Rstudio cloud](https://rstudio.cloud), [RStudio online on rollapp](https://www.rollapp.com/app/rstudio), [R-bloggers](https://www.r-bloggers.com/)

### Занятие 1. Введение в R и RStudio. Вектор. Датафрем. Установка и работа с пакетами.

* [материалы занятия](https://agricolamz.github.io/2018_FE_R_statistics/Lab_1.html)
* [домашнее задание](https://docs.google.com/forms/d/e/1FAIpQLScLWNxqwls7ZDxB7S4OyhOWM3U86g-PSwxYfNpSWHqme5KiQQ/viewform?c=0&w=1)

### Занятие 2. Пользовательские функции. Пакет tidyverse.

* [материалы занятия](https://agricolamz.github.io/2018_FE_R_statistics/Lab_2.html)
* [домашнее задание](https://docs.google.com/forms/d/e/1FAIpQLSd4R-RgfVA8RJm0DqMZZhuH-T3uuHpiqb0H-F8yyyKB7zJihg/viewform?c=0&w=1)

### Занятие 3. Joins. Работа со строками. Пакет stringr

* [материалы занятия](https://agricolamz.github.io/2018_FE_R_statistics/Lab_3.html)
* [презентация]()
* [домашнее задание]()

### Занятие 4. Визуализация. Пакет ggplot2. RMarkdown.

* [материалы занятия](https://agricolamz.github.io/2018_FE_R_statistics/Lab_4.html)
* [презентация]()

### Занятие 5. Визуализация. Пакет ggplot2. Plotly. Shiny

* [материалы занятия]()
* [домашнее задание]()

### Занятие 6. Повторение.

* [задания]()

### Занятия 7-8. Описантельная статистика. Фриквентистская статистика

* [материалы занятия]()
* [презентация]()
* [домашнее задание]()

### Занятие 9. Корреляция и регрессия

* [материалы занятия]()
* [презентация]()

### Занятие 10. Повторение и логистическая регрессия

* [материалы занятия]()
* [презентация]()
* домашнее задание

### Занятие 11. Кластеризация и деревья решений

* [презентация]()
* [материалы занятия]()